name: Deploy docs to website

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cat mkdoc.yml
